### ISSUE TITLE
MissinModules Error for "https", "crypto"

### ISSUE THREAD

**Issue by mohithgupta** [Tilak999/jsonbase.com#2]
![Screenshot (275)](https://user-images.githubusercontent.com/50448748/147552082-8de218c4-a4f6-483f-b76c-f2f9d85c18ea.png)

**Comment by mohithgupta** [comment]
By the way, I have them installed in my project but I dont think I should have need to do that manually rght? I'm just not able get my head around this issue. Please help!

**Comment by tilak999** [comment]
It looks like you are trying to use the package in a frontend node application.

Webpack can't bundle the https and crypto packages because these are native nodejs packages.

You shouldn't use this package from a frontend as the storage/bucket keys will be exposed. But if you must then you can use the REST APIs directly.
